language: scala

# This is only necessary for trying out oraclejdk9, which doesn't yet work on their side
# sudo: false
# dist: trusty

scala:
  - 2.11.12
  - 2.12.6
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

script:
  - sbt clean coverage test coverageReport package package-doc

after_success:
  - bash <(curl -s https://codecov.io/bash)
